#cloud-config

package_update: true
package_upgrade: true

packages:
 - git
 - rabbitmq-server
 - python-pip
 - python-swiftclient

runcmd:
 - pip install Celery
 - pip install Flask
 - pip install python-swiftclient
 - git clone https://github.com/DrThyme/Applied-Cloud-Computing.git
 - chmod -R 777 /home/ubuntu/Applied-Cloud-Computing
